name: Run Terra Featured Workspace Tests
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 */14 * *' # Every 2 weeks on Sunday at 00:00 UTC
  workflow_dispatch:
    inputs:
      mute_notifications:
          description: 'Mute notifications'
          default: 'true'
          required: false
      troubleshoot:
          description: 'Enable troubleshooting'
          default: 'true'
          required: false

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
  GCP_PROJECT_ID: "terra-featured-workspace-tests"
  GCP_SA_EMAIL: "terra-featured-workspace-tests@terra-featured-workspace-tests.iam.gserviceaccount.com"
jobs:
  run-featured-workspace-tests:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          workload_identity_provider: "projects/953233968740/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: ${{ env.GCP_SA_EMAIL }}

      - id: secrets
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: |-
            sendgrid_key:${{ env.GCP_PROJECT_ID }}/sendgrid_key

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          

      - name: Debug constructed command
        run: |
          set -e
          CURRENT_DATE=$(date +%Y-%m-%d-%H-%M-%S)
          REPORT_NAME="master_report_${CURRENT_DATE}.html"
          echo "Constructed command:"
          echo "python3 -u featured_workspaces_test.py -n \"$REPORT_NAME\" -v --gcs_path \"gs://terra-featured-workspace-tests-reports/fw_reports/\" $([[ \"${{ github.event.inputs.mute_notifications }}\" == 'true' ]] && echo \"--mute_notifications\") $([[ \"${{ github.event.inputs.troubleshoot }}\" == 'true' ]] && echo \"--troubleshoot\")"
          echo "Running command..."
          echo "Input: mute_notifications = '${{ github.event.inputs.mute_notifications }}'"
          echo "Input: troubleshoot = '${{ github.event.inputs.troubleshoot }}'"
          

      - name: Construct Command
        run: |
          set -e
          CURRENT_DATE=$(date +%Y-%m-%d-%H-%M-%S)
          REPORT_NAME="master_report_${CURRENT_DATE}.html"
          CMD="python3 -u featured_workspaces_test.py -n \"$REPORT_NAME\" -v --gcs_path \"gs://terra-featured-workspace-tests-reports/fw_reports/\""
      
          # Append flags based on inputs
          if [[ "${{ github.event.inputs.mute_notifications }}" == 'true' ]]; then
            CMD="$CMD --mute_notifications"
          fi
          if [[ "${{ github.event.inputs.troubleshoot }}" == 'true' ]]; then
            CMD="$CMD --troubleshoot"
          fi
      
          echo "Constructed command: $CMD"
          echo $CMD > run_command.sh


      - name: Run Terra Featured Workspace Tests
        env:
          SENDGRID_KEY: ${{ steps.secrets.outputs.sendgrid_key }}
        run: |
          set -e
          CURRENT_DATE=$(date +%Y-%m-%d-%H-%M-%S)
          REPORT_NAME="master_report_${CURRENT_DATE}.html"
          python3 -u featured_workspaces_test.py \
            -n "$REPORT_NAME" \
            -v \
            --gcs_path "gs://terra-featured-workspace-tests-reports/fw_reports/" \
            $([[ "${{ github.event.inputs.mute_notifications }}" == 'true' ]] && echo "--mute_notifications") \
            $([[ "${{ github.event.inputs.troubleshoot }}" == 'true' ]] && echo "--troubleshoot")

