name: Run Terra Featured Workspace Tests
on:
  schedule:
    - cron: '0 0 */14 * *' # Every 2 weeks on Sunday at 00:00 UTC
  workflow_dispatch:
    inputs:
      mute_notifications:
          description: 'Mute notifications'
          default: 'true'
          required: false
      troubleshoot:
          description: 'Enable troubleshooting'
          default: 'true'
          required: false

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
  GCP_PROJECT_ID: "terra-featured-workspace-tests"
  GCP_SA_EMAIL: "terra-featured-workspace-tests@terra-featured-workspace-tests.iam.gserviceaccount.com"
jobs:
  run-featured-workspace-tests:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate CURRENT_DATE
        id: date
        run: |
          echo "CURRENT_DATE=$(date +%Y-%m-%d-%H-%M-%S)" >> $GITHUB_ENV
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          workload_identity_provider: "projects/953233968740/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: ${{ env.GCP_SA_EMAIL }}

      - id: secrets
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: |-
            sendgrid_key:${{ env.GCP_PROJECT_ID }}/sendgrid_key

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Run Terra Featured Workspace Tests
        env:
          SENDGRID_KEY: ${{ steps.secrets.outputs.sendgrid_key }}
        run: |
          set -e
          REPORT_NAME="master_report_${CURRENT_DATE}.html"
          python3 -u featured_workspaces_test.py \
            -n "$REPORT_NAME" \
            -v \
            --gcs_path "gs://terra-featured-workspace-tests-reports/fw_reports/" \
            $([[ "${{ github.event.inputs.mute_notifications }}" == 'true' ]] && echo "--mute_notifications") \
            $([[ "${{ github.event.inputs.troubleshoot }}" == 'true' ]] && echo "--troubleshoot")

      - name: Send custom event details to a Slack workflow
        if: ${{ github.event.inputs.mute_notifications != 'true' }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            is_successful: "${{ github.action_status}}"
            report_url: "https://storage.googleapis.com/terra-featured-workspace-tests-reports/fw_reports/master_report_${{env.CURRENT_DATE}}.html"
            run_url: "${{github.run_number}}"
